# Generated by Django 2.0.6 on 2018-11-11 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181111_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='activationString',
            new_name='activationKey',
        ),
    ]
