# Generated by Django 2.1.7 on 2019-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, max_length=1023)),
                ('subjectArea', models.CharField(choices=[('general', 'General'), ('programming1', 'Programming 1'), ('programming2', 'Programming 2'), ('programming3', 'Programming 3'), ('programming4', 'Programming 4'), ('web-client-development', 'Web Client Development'), ('web-server-development', 'Web Server Development'), ('web-design', 'Web Design'), ('databases', 'Databases'), ('networking1', 'Networking 1'), ('networking2', 'Networking 2'), ('security1', 'Cyber Security 1'), ('security2', 'Cyber Security 2'), ('linux', 'Linux'), ('embedded', 'Embedded Systems'), ('python', 'Python'), ('c', 'C/C++'), ('java', 'Java'), ('javascript', 'Javascript'), ('php', 'PHP'), ('servers', 'Servers')], default=1, max_length=30)),
                ('entryDate', models.DateField(auto_now_add=True)),
                ('modificationDate', models.DateField(auto_now=True)),
                ('articleURL', models.URLField()),
            ],
        ),
    ]
