# Generated by Django 2.1.7 on 2019-05-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesupport', '0002_auto_20190409_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='summaryText',
        ),
        migrations.AlterField(
            model_name='course',
            name='subjectArea',
            field=models.CharField(choices=[('web-client-development', 'Web Client Development'), ('web-server-development', 'Web Server Development'), ('web-design', 'Web Design'), ('databases', 'Databases'), ('networking1', 'Networking'), ('security1', 'Cyber Security'), ('linux', 'Linux'), ('embedded', 'Embedded Systems'), ('python', 'Python'), ('django', 'Django'), ('sass', 'Sass'), ('c', 'C/C++'), ('java', 'Java'), ('javascript', 'Javascript'), ('php', 'PHP'), ('servers', 'Servers')], default=1, max_length=30),
        ),
    ]
