# Generated by Django 2.0.6 on 2018-07-30 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subjectArea', models.CharField(choices=[('general', 'General'), ('programming1', 'Programming 1'), ('programming2', 'Programming 2'), ('programming3', 'Programming 3'), ('web-client-development', 'Web Client Development'), ('web-server-development', 'Web Server Development'), ('web-design', 'Web Design'), ('databases', 'Databases'), ('networking1', 'Networking 1'), ('networking2', 'Networking 2'), ('security1', 'Cyber Security 1'), ('security2', 'Cyber Security 2'), ('linux', 'Linux'), ('embedded', 'Embedded Systems'), ('python', 'Python'), ('c', 'C/C++'), ('java', 'Java'), ('javascript', 'Javascript'), ('servers', 'Servers')], default=1, max_length=20)),
                ('subjectAreaSecondary', models.CharField(choices=[('general', 'General'), ('programming1', 'Programming 1'), ('programming2', 'Programming 2'), ('programming3', 'Programming 3'), ('web-client-development', 'Web Client Development'), ('web-server-development', 'Web Server Development'), ('web-design', 'Web Design'), ('databases', 'Databases'), ('networking1', 'Networking 1'), ('networking2', 'Networking 2'), ('security1', 'Cyber Security 1'), ('security2', 'Cyber Security 2'), ('linux', 'Linux'), ('embedded', 'Embedded Systems'), ('python', 'Python'), ('c', 'C/C++'), ('java', 'Java'), ('javascript', 'Javascript'), ('servers', 'Servers')], default=1, max_length=20)),
                ('entryDate', models.DateField(auto_now_add=True)),
                ('modificationDate', models.DateField(auto_now_add=True)),
                ('articleURL', models.URLField()),
                ('author', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.CharField(max_length=10)),
                ('semester', models.TextField(choices=[('fall', 'Fall'), ('winter', 'Winter'), ('spring', 'Spring'), ('summer1', 'Summer 1'), ('summer2', 'Summer 2')], max_length=12)),
                ('year', models.DateField()),
                ('startTime', models.TimeField()),
                ('length', models.TimeField(default=5100)),
                ('subjectArea', models.CharField(choices=[('general', 'General'), ('programming1', 'Programming 1'), ('programming2', 'Programming 2'), ('programming3', 'Programming 3'), ('web-client-development', 'Web Client Development'), ('web-server-development', 'Web Server Development'), ('web-design', 'Web Design'), ('databases', 'Databases'), ('networking1', 'Networking 1'), ('networking2', 'Networking 2'), ('security1', 'Cyber Security 1'), ('security2', 'Cyber Security 2'), ('linux', 'Linux'), ('embedded', 'Embedded Systems'), ('python', 'Python'), ('c', 'C/C++'), ('java', 'Java'), ('javascript', 'Javascript'), ('servers', 'Servers')], default=1, max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
