# Generated by Django 2.0.6 on 2018-07-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180730_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
