# Generated by Django 2.0.6 on 2018-08-04 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180802_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('semesterName', models.TextField(choices=[('fall', 'Fall'), ('winter', 'Winter'), ('spring', 'Spring'), ('summer1', 'Summer 1'), ('summer2', 'Summer 2')], default='fall', max_length=12)),
            ],
        ),
        migrations.RenameField(
            model_name='classschedule',
            old_name='semester',
            new_name='semesterName',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='courseTitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='roomNumber',
            field=models.TextField(default='AC008', max_length=8),
        ),
        migrations.AddField(
            model_name='semester',
            name='classSchedules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.ClassSchedule'),
        ),
    ]
