# Generated by Django 2.0.6 on 2018-08-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_summarytext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summaryText',
            field=models.TextField(blank=True, max_length=1023),
        ),
    ]
