# Generated by Django 2.0.6 on 2018-08-21 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_classschedule_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classschedule',
            old_name='days',
            new_name='runningOnDays',
        ),
    ]
