# Generated by Django 2.0.6 on 2018-08-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20180821_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='year',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='runningInYear',
            field=models.IntegerField(choices=[(2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=2018),
        ),
    ]
