# Generated by Django 2.0.6 on 2018-08-21 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20180821_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='year',
        ),
    ]
