# Generated by Django 2.0.6 on 2018-08-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_semester_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.IntegerField(choices=[(2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=2018),
        ),
    ]
