# Generated by Django 2.0.6 on 2018-08-21 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20180821_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='classSchedules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.ClassSchedule'),
        ),
    ]
