# Generated by Django 2.0.6 on 2018-08-23 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20180823_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='author',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
