# Generated by Django 2.0.6 on 2018-08-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20180823_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.CharField(max_length=10)),
                ('courseSubjectArea', models.CharField(choices=[('general', 'General'), ('programming1', 'Programming 1'), ('programming2', 'Programming 2'), ('programming3', 'Programming 3'), ('web-client-development', 'Web Client Development'), ('web-server-development', 'Web Server Development'), ('web-design', 'Web Design'), ('databases', 'Databases'), ('networking1', 'Networking 1'), ('networking2', 'Networking 2'), ('security1', 'Cyber Security 1'), ('security2', 'Cyber Security 2'), ('linux', 'Linux'), ('embedded', 'Embedded Systems'), ('python', 'Python'), ('c', 'C/C++'), ('java', 'Java'), ('javascript', 'Javascript'), ('php', 'PHP'), ('servers', 'Servers')], default=1, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='subjectArea',
            field=models.CharField(choices=[('general', 'General'), ('programming1', 'Programming 1'), ('programming2', 'Programming 2'), ('programming3', 'Programming 3'), ('web-client-development', 'Web Client Development'), ('web-server-development', 'Web Server Development'), ('web-design', 'Web Design'), ('databases', 'Databases'), ('networking1', 'Networking 1'), ('networking2', 'Networking 2'), ('security1', 'Cyber Security 1'), ('security2', 'Cyber Security 2'), ('linux', 'Linux'), ('embedded', 'Embedded Systems'), ('python', 'Python'), ('c', 'C/C++'), ('java', 'Java'), ('javascript', 'Javascript'), ('php', 'PHP'), ('servers', 'Servers')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='subjectAreaSecondary',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('programming1', 'Programming 1'), ('programming2', 'Programming 2'), ('programming3', 'Programming 3'), ('web-client-development', 'Web Client Development'), ('web-server-development', 'Web Server Development'), ('web-design', 'Web Design'), ('databases', 'Databases'), ('networking1', 'Networking 1'), ('networking2', 'Networking 2'), ('security1', 'Cyber Security 1'), ('security2', 'Cyber Security 2'), ('linux', 'Linux'), ('embedded', 'Embedded Systems'), ('python', 'Python'), ('c', 'C/C++'), ('java', 'Java'), ('javascript', 'Javascript'), ('php', 'PHP'), ('servers', 'Servers')], max_length=30),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='subjectArea',
            field=models.CharField(choices=[('general', 'General'), ('programming1', 'Programming 1'), ('programming2', 'Programming 2'), ('programming3', 'Programming 3'), ('web-client-development', 'Web Client Development'), ('web-server-development', 'Web Server Development'), ('web-design', 'Web Design'), ('databases', 'Databases'), ('networking1', 'Networking 1'), ('networking2', 'Networking 2'), ('security1', 'Cyber Security 1'), ('security2', 'Cyber Security 2'), ('linux', 'Linux'), ('embedded', 'Embedded Systems'), ('python', 'Python'), ('c', 'C/C++'), ('java', 'Java'), ('javascript', 'Javascript'), ('php', 'PHP'), ('servers', 'Servers')], default=1, max_length=20),
        ),
    ]
