# Generated by Django 2.0.6 on 2018-11-04 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='comicstrip/images/')),
                ('summaryText', models.TextField(blank=True, max_length=1023)),
                ('current', models.BooleanField(default=True)),
                ('entryDate', models.DateField(auto_now_add=True)),
                ('modificationDate', models.DateField(auto_now=True)),
                ('vetted', models.BooleanField(default=False)),
                ('comicAuthor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comicAuthor', to=settings.AUTH_USER_MODEL)),
                ('comicVettedBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comicVettedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
