# Generated by Django 2.0.6 on 2018-07-28 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bodyText', models.TextField()),
                ('entryDate', models.DateField(auto_now_add=True)),
                ('startDate', models.DateField()),
                ('expirationDate', models.DateField()),
                ('modificationDate', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullCourseNumber', models.CharField(max_length=10, unique=True)),
                ('discipline', models.CharField(choices=[('AC', 'Accounting'), ('AR', 'Art'), ('CO', 'Communication'), ('CS', 'Computer Science'), ('CJ', 'Criminal Justice'), ('CU', 'Culinary Arts'), ('EN', 'English'), ('FS', 'Food/Resturant Service Mgmt'), ('GD', 'Graphic Design'), ('HA', 'Health Care Mgmt'), ('HO', 'Honors'), ('HR', 'Hotel/Resort Mgmt'), ('HU', 'Humanities'), ('ID', 'Interior Design'), ('MN', 'Management'), ('MK', 'Marketing'), ('MH', 'Mathematics'), ('PM', 'PM'), ('LW', 'Pre-Law'), ('PS', 'Psychology'), ('SC', 'Science'), ('SS', 'Social Science'), ('SM', 'Sports Management'), ('HR', 'Human Resource Mgmt.')], max_length=50, unique=True)),
                ('courseTitle', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.TextField(max_length=50, unique=True)),
                ('topicComments', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='relatedCourseNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.CourseNumber'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.Topics'),
        ),
    ]
