# Generated by Django 2.0.6 on 2018-07-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='relatedCourseNumber',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='announcements.CourseNumber'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topicComments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
