# Generated by Django 2.0.6 on 2018-07-30 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20180730_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='relatedCourseNumber',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='announcements.CourseNumber'),
        ),
    ]
