# Generated by Django 2.0.6 on 2018-07-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20180730_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursenumber',
            name='discipline',
            field=models.CharField(choices=[('XX', 'None'), ('AC', 'Accounting'), ('AR', 'Art'), ('CO', 'Communication'), ('CS', 'Computer Science'), ('CJ', 'Criminal Justice'), ('CU', 'Culinary Arts'), ('EN', 'English'), ('FS', 'Food/Resturant Service Mgmt'), ('GD', 'Graphic Design'), ('HA', 'Health Care Mgmt'), ('HO', 'Honors'), ('HR', 'Hotel/Resort Mgmt'), ('HU', 'Humanities'), ('ID', 'Interior Design'), ('MN', 'Management'), ('MK', 'Marketing'), ('MH', 'Mathematics'), ('PM', 'PM'), ('LW', 'Pre-Law'), ('PS', 'Psychology'), ('SC', 'Science'), ('SS', 'Social Science'), ('SM', 'Sports Management'), ('HR', 'Human Resource Mgmt.')], max_length=50, unique=True),
        ),
    ]
