# Generated by Django 2.0.6 on 2018-07-30 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20180730_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='relatedCourseNumber',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='announcements.CourseNumber'),
        ),
    ]
