# Generated by Django 2.0.6 on 2018-07-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_auto_20180730_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='color',
            field=models.CharField(choices=[('', 'None'), ('bg-primary', 'Primary'), ('bg-secondary', 'Secondary'), ('bg-success', 'Success'), ('bg-info', 'Info'), ('bg-warning', 'Warning'), ('bg-danger', 'Danger'), ('bg-light', 'Light'), ('bg-dark', 'Dark')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
